# Generated by Django 3.2.7 on 2021-10-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpath', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respite',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
